export const data = [
  {
    name: "Flora",
    src: "https://i.imgur.com/omNs6Sg.jpg",
    width: 2481,
    height: 3419,
  },
  {
    name: "Ruby",
    src: "https://i.imgur.com/uWU4Kfc.jpg",
    width: 2837,
    height: 2505,
  },
  {
    name: "Sunny",
    src: "https://i.imgur.com/xvmj1wo.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Cutie",
    src: "https://i.imgur.com/1XaHJ08.jpg",
    width: 1280,
    height: 960,
  },
  {
    name: "Lotje",
    src: "https://i.imgur.com/eoagg6P.jpg",
    width: 960,
    height: 1280,
  },
  {
    name: "Apollo",
    src: "https://i.imgur.com/XepMcaX.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Olive",
    src: "https://i.imgur.com/5HbXY0A.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Blinky",
    src: "https://i.imgur.com/y3mY50q.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Oscar",
    src: "https://i.imgur.com/5Q3VLw6.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Zoe",
    src: "https://i.imgur.com/neCkjlw.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Tater",
    src: "https://i.imgur.com/7TWKzu1.jpg",
    width: 750,
    height: 754,
  },
  {
    name: "Calvin",
    src: "https://i.imgur.com/KoXQmrO.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Thor",
    src: "https://i.imgur.com/KWBEzz6.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Lyla",
    src: "https://i.imgur.com/1tEfPxE.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Hugo",
    src: "https://i.imgur.com/zlbhVQg.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Jughead",
    src: "https://i.imgur.com/4dt6zaX.png",
    width: 892,
    height: 892,
  },
  {
    name: "Thor and Loki",
    src: "https://i.imgur.com/IZegZC5.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Kallisto",
    src: "https://i.imgur.com/4GjDPET.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Sammy",
    src: "https://i.imgur.com/LSkVsqc.jpg",
    width: 1512,
    height: 2016,
  },
  {
    name: "Emanon",
    src: "https://i.imgur.com/U5eXuNy.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Daisyo",
    src: "https://i.imgur.com/jNadi7N.jpg",
    width: 2500,
    height: 1667,
  },
  {
    name: "Newton",
    src: "https://i.imgur.com/nWNLvsA.png",
    width: 750,
    height: 992,
  },
  {
    name: "Lincoln",
    src: "https://i.imgur.com/p9usOvy.jpg",
    width: 640,
    height: 480,
  },
  {
    name: "Cooper",
    src: "https://i.imgur.com/Y5Npolr.jpg",
    width: 480,
    height: 640,
  },
  {
    name: "Dexter",
    src: "https://i.imgur.com/OaxXent.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Goiabada",
    src: "https://i.imgur.com/4V8cqZl.jpg",
    width: 768,
    height: 1024,
  },
  {
    name: "Wooner",
    src: "https://i.imgur.com/gU8LFGG.jpg",
    width: 2048,
    height: 1360,
  },
  {
    name: "Woz",
    src: "https://i.imgur.com/INdkj4o.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Regulus",
    src: "https://i.imgur.com/BloehF8.jpg",
    width: 2048,
    height: 1536,
  },
  {
    name: "Charlie",
    src: "https://i.imgur.com/f6HFUk4.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Scronch",
    src: "https://i.imgur.com/EpbNMmS.jpg",
    width: 934,
    height: 2048,
  },
  {
    name: "Takito",
    src: "https://i.imgur.com/lylYnqo.jpg",
    width: 2048,
    height: 2048,
  },
  {
    name: "Bacardi and Tito",
    src: "https://i.imgur.com/DhxB19P.jpg",
    width: 2048,
    height: 1536,
  },
  {
    name: "Koji San",
    src: "https://i.imgur.com/0KDUtY5.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Ernest",
    src: "https://i.imgur.com/d9o8m47.jpg",
    width: 1024,
    height: 768,
  },
  {
    name: "Romfph",
    src: "https://i.imgur.com/NhFyl4f.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Lucky",
    src: "https://i.imgur.com/z04VB01.jpg",
    width: 1040,
    height: 2048,
  },
  {
    name: "Zeus and Kiara",
    src: "https://i.imgur.com/xqrgXUz.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Sam",
    src: "https://i.imgur.com/3nIEP3E.jpg",
    width: 2048,
    height: 1536,
  },
  {
    name: "Hoss",
    src: "https://i.imgur.com/ejpsjya.jpg",
    width: 768,
    height: 1024,
  },
  {
    name: "Basil",
    src: "https://i.imgur.com/TKXNew9.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Ruby",
    src: "https://i.imgur.com/u6CqCBR.jpg",
    width: 2346,
    height: 3757,
  },
  {
    name: "Chloe",
    src: "https://i.imgur.com/3MeNh4z.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Spot",
    src: "https://i.imgur.com/WhErjdp.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Willow and Lucylou",
    src: "https://i.imgur.com/ntAUJ3T.jpg",
    width: 2048,
    height: 1536,
  },
  {
    name: "Pinto",
    src: "https://i.imgur.com/mXvyfUF.jpg",
    width: 1200,
    height: 1600,
  },
  {
    name: "Dennis",
    src: "https://i.imgur.com/Wfz0ngn.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Lexi",
    src: "https://i.imgur.com/THCLcJt.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Kageyama",
    src: "https://i.imgur.com/Zo34c7E.jpg",
    width: 1512,
    height: 2016,
  },
  {
    name: "Oli",
    src: "https://i.imgur.com/KI9bBgq.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Robu",
    src: "https://i.imgur.com/2iruiXG.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Ukai",
    src: "https://i.imgur.com/KOnCN1B.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Maachis",
    src: "https://i.imgur.com/cIcUiZ4.jpg",
    width: 1080,
    height: 1616,
  },
  {
    name: "Maggie",
    src: "https://i.imgur.com/FHbdRvS.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Iwaizumi",
    src: "https://i.imgur.com/cVmgcgI.jpg",
    width: 1668,
    height: 1250,
  },
  {
    name: "Jino",
    src: "https://i.imgur.com/QEek3qu.jpg",
    width: 2448,
    height: 2448,
  },
  {
    name: "Lev",
    src: "https://i.imgur.com/KKoQhFK.jpg",
    width: 924,
    height: 1280,
  },
  {
    name: "Penny",
    src: "https://i.imgur.com/oM8T2Oh.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Bokuto and Akashi",
    src: "https://i.imgur.com/ekG3IeV.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Lilly",
    src: "https://i.imgur.com/lVyQJGz.jpg",
    width: 2500,
    height: 1669,
  },
  {
    name: "Louis",
    src: "https://i.imgur.com/3yKffCz.jpg",
    width: 2448,
    height: 3264,
  },
  {
    name: "Zoe",
    src: "https://i.imgur.com/vkkzZJi.jpg",
    width: 1348,
    height: 1798,
  },
  {
    name: "Brownie",
    src: "https://i.imgur.com/foOmVcT.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Captain",
    src: "https://i.imgur.com/CxgG90a.jpg",
    width: 2000,
    height: 3000,
  },
  {
    name: "Pudding",
    src: "https://i.imgur.com/BQDsZgN.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Scarlet and Franco",
    src: "https://i.imgur.com/Tro8oly.jpg",
    width: 2368,
    height: 3200,
  },
  {
    name: "Zafira",
    src: "https://i.imgur.com/xJqcJWE.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Joey",
    src: "https://i.imgur.com/8ug1RLT.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Lady",
    src: "https://i.imgur.com/jlAi6p4.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Rosco",
    src: "https://i.imgur.com/0dZ5SVy.jpg",
    width: 960,
    height: 1280,
  },
  {
    name: "Lola",
    src: "https://i.imgur.com/cJmJCy4.jpg",
    width: 2048,
    height: 1536,
  },
  {
    name: "Otis and Millie",
    src: "https://i.imgur.com/nVDV7ZC.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Abi",
    src: "https://i.imgur.com/mYpHNIl.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Paul and Lucy",
    src: "https://i.imgur.com/VHlF2qb.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Luna",
    src: "https://i.imgur.com/Sj4bHIg.jpg",
    width: 3730,
    height: 2487,
  },
  {
    name: "Victor",
    src: "https://i.imgur.com/zqFt8e9.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Noodle",
    src: "https://i.imgur.com/xzZXXh5.jpg",
    width: 750,
    height: 736,
  },
  {
    name: "Misha",
    src: "https://i.imgur.com/KEdY4Ng.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Aone",
    src: "https://i.imgur.com/qzSlbfZ.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Clyde",
    src: "https://i.imgur.com/It3pKLU.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Honey",
    src: "https://i.imgur.com/2kUUsuE.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Buttercup",
    src: "https://i.imgur.com/2UdZ3uP.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Kenma",
    src: "https://i.imgur.com/VYqHrtx.jpg",
    width: 1280,
    height: 854,
  },
  {
    name: "Gandalf",
    src: "https://i.imgur.com/dUo7mMj.jpg",
    width: 960,
    height: 1280,
  },
  {
    name: "Margot",
    src: "https://i.imgur.com/xwWltli.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Emma",
    src: "https://i.imgur.com/00S9q9Z.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Foggy",
    src: "https://i.imgur.com/myiX6rk.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Mickey",
    src: "https://i.imgur.com/ypOo1R7.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Nermal",
    src: "https://i.imgur.com/Zsfoesl.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Findus",
    src: "https://i.imgur.com/iFW0ivP.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Potato",
    src: "https://i.imgur.com/MNICH8W.jpg",
    width: 2927,
    height: 3660,
  },
  {
    name: "Mew",
    src: "https://i.imgur.com/dlgPk6I.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Marty Byrde",
    src: "https://i.imgur.com/udeCmE2.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Boots",
    src: "https://i.imgur.com/BX8B2Yl.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Sansa and Fleur",
    src: "https://i.imgur.com/C8q0DJb.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Dempsey",
    src: "https://i.imgur.com/SPlbfJn.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Bruno and Zixten",
    src: "https://i.imgur.com/1I3z7NQ.jpg",
    width: 750,
    height: 738,
  },
  {
    name: "Choco",
    src: "https://i.imgur.com/v7BOohM.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Ronnie",
    src: "https://i.imgur.com/wksNBPw.jpg",
    width: 744,
    height: 992,
  },
  {
    name: "Tongana",
    src: "https://i.imgur.com/2vfKJ9R.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Daisy",
    src: "https://i.imgur.com/K8htmnn.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Klohe",
    src: "https://i.imgur.com/CXX7dXe.jpg",
    width: 1242,
    height: 1652,
  },
  {
    name: "Gubbins",
    src: "https://i.imgur.com/DPprkBk.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Pixel",
    src: "https://i.imgur.com/bbsU3BQ.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Chaya",
    src: "https://i.imgur.com/O3kg7Ti.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Jasper",
    src: "https://i.imgur.com/IzWbcye.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Fiver and Pfeffer",
    src: "https://i.imgur.com/IM2XRho.jpg",
    width: 3024,
    height: 3024,
  },
  {
    name: "Ruby",
    src: "https://i.imgur.com/XWUeyoQ.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Lady and Cleo",
    src: "https://i.imgur.com/0EMgBRa.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Nutmeg",
    src: "https://i.imgur.com/1eBDEmG.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Thandie",
    src: "https://i.imgur.com/7ig14SV.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Onyx",
    src: "https://i.imgur.com/S0t8gwN.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Cobalt",
    src: "https://i.imgur.com/ORPGi98.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Milly",
    src: "https://i.imgur.com/kXHgkjU.jpg",
    width: 1512,
    height: 2016,
  },
  {
    name: "Demie",
    src: "https://i.imgur.com/GvqNwfV.jpg",
    width: 1773,
    height: 1773,
  },
  {
    name: "Lua",
    src: "https://i.imgur.com/ZtLbMJg.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Negra",
    src: "https://i.imgur.com/9v3zPDO.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Sunny",
    src: "https://i.imgur.com/86WNyRx.jpg",
    width: 1125,
    height: 1962,
  },
  {
    name: "Annie",
    src: "https://i.imgur.com/VhDcBcj.jpg",
    width: 2448,
    height: 3264,
  },
  {
    name: "Kepler",
    src: "https://i.imgur.com/SAlTJRm.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Mitzi",
    src: "https://i.imgur.com/Z7Y7dgy.jpg",
    width: 2510,
    height: 3137,
  },
  {
    name: "Freddie",
    src: "https://i.imgur.com/6cDx1cM.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Abby",
    src: "https://i.imgur.com/dxQ8Vz7.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Oliver",
    src: "https://i.imgur.com/UKpMBqs.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Nebula",
    src: "https://i.imgur.com/AzKWNMe.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Bella",
    src: "https://i.imgur.com/eDyTZdu.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Daisy and Nitro",
    src: "https://i.imgur.com/fuqxLCX.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Whiskey",
    src: "https://i.imgur.com/2JDB0Hv.jpg",
    width: 970,
    height: 1296,
  },
  {
    name: "Polly",
    src: "https://i.imgur.com/aNIY1Pg.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Lana",
    src: "https://i.imgur.com/G1gnNWr.jpg",
    width: 2048,
    height: 1989,
  },
  {
    name: "Hawk",
    src: "https://i.imgur.com/ZMGylVb.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Max",
    src: "https://i.imgur.com/7G0nU0c.jpg",
    width: 768,
    height: 1024,
  },
  {
    name: "Scotty",
    src: "https://i.imgur.com/bTYG8th.jpg",
    width: 598,
    height: 598,
  },
  {
    name: "Atticus",
    src: "https://i.imgur.com/4keAZva.jpg",
    width: 960,
    height: 1280,
  },
  {
    name: "Mojo",
    src: "https://i.imgur.com/SMufrCz.jpg",
    width: 2448,
    height: 3264,
  },
  {
    name: "Queen Bae",
    src: "https://i.imgur.com/7VSQIbI.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Lexi",
    src: "https://i.imgur.com/6tl1oTk.jpg",
    width: 2316,
    height: 3088,
  },
  {
    name: "Milo",
    src: "https://i.imgur.com/V07nLZT.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Cuba",
    src: "https://i.imgur.com/q1MaSyS.jpg",
    width: 2323,
    height: 2119,
  },
  {
    name: "Hectorine",
    src: "https://i.imgur.com/Q14BG3b.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Mayonaka",
    src: "https://i.imgur.com/i08CCw1.jpg",
    width: 2048,
    height: 1536,
  },
  {
    name: "Lucy",
    src: "https://i.imgur.com/RczJH65.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Kitty",
    src: "https://i.imgur.com/4Flzhl4.jpg",
    width: 523,
    height: 467,
  },
  {
    name: "Apollo",
    src: "https://i.imgur.com/sHxvJWz.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Mikey, Lilly, Stevie and Jessie",
    src: "https://i.imgur.com/Dch36Yo.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Harley",
    src: "https://i.imgur.com/WVbg388.jpg",
    width: 480,
    height: 640,
  },
  {
    name: "Meena",
    src: "https://i.imgur.com/bbJfW2m.jpg",
    width: 640,
    height: 480,
  },
  {
    name: "Biscuit",
    src: "https://i.imgur.com/INPRUFz.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Blue",
    src: "https://i.imgur.com/XdmxXrZ.jpg",
    width: 972,
    height: 1296,
  },
  {
    name: "Caspar",
    src: "https://i.imgur.com/WXwrGlA.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Bessie",
    src: "https://i.imgur.com/1fYU3EM.jpg",
    width: 2096,
    height: 3724,
  },
  {
    name: "Haru",
    src: "https://i.imgur.com/sHCuzMB.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Callie",
    src: "https://i.imgur.com/mM16rBM.jpg",
    width: 2316,
    height: 3088,
  },
  {
    name: "Doc",
    src: "https://i.imgur.com/ufojybY.jpg",
    width: 1325,
    height: 2006,
  },
  {
    name: "Kiki and Kiki",
    src: "https://i.imgur.com/19WcIZ3.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Mimi",
    src: "https://i.imgur.com/OSvtDIv.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Rocket",
    src: "https://i.imgur.com/zKYJwbC.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Bea",
    src: "https://i.imgur.com/A9Pzvh4.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Alfred",
    src: "https://i.imgur.com/GB68oXK.jpg",
    width: 1536,
    height: 2049,
  },
  {
    name: "Leo",
    src: "https://i.imgur.com/XDxNmat.jpg",
    width: 1242,
    height: 1542,
  },
  {
    name: "Rick",
    src: "https://i.imgur.com/lnMSqo1.jpg",
    width: 960,
    height: 1280,
  },
  {
    name: "Thunder and Lightning",
    src: "https://i.imgur.com/cUZoADI.jpg",
    width: 2016,
    height: 1512,
  },
  {
    name: "Blixt",
    src: "https://i.imgur.com/Duabce8.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Lucas",
    src: "https://i.imgur.com/OW4lbkj.jpg",
    width: 768,
    height: 1024,
  },
  {
    name: "Leonard",
    src: "https://i.imgur.com/pits6MV.jpg",
    width: 750,
    height: 965,
  },
  {
    name: "Yewtree",
    src: "https://i.imgur.com/qQGUMPx.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Scooter",
    src: "https://i.imgur.com/kMshDrX.jpg",
    width: 960,
    height: 1280,
  },
  {
    name: "Snickers",
    src: "https://i.imgur.com/Q5BUxnm.jpg",
    width: 2415,
    height: 3220,
  },
  {
    name: "Geronimo",
    src: "https://i.imgur.com/k8ycppT.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Olaf and Bella",
    src: "https://i.imgur.com/vpuhx00.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Cliff",
    src: "https://i.imgur.com/0MKO41S.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Bushy and Scrup",
    src: "https://i.imgur.com/hnfqNJm.jpg",
    width: 2048,
    height: 1536,
  },
  {
    name: "Fiona",
    src: "https://i.imgur.com/0Kvo4n7.jpg",
    width: 1122,
    height: 1840,
  },
  {
    name: "Chicka",
    src: "https://i.imgur.com/tWgKJCZ.jpg",
    width: 2048,
    height: 1536,
  },
  {
    name: "Obi",
    src: "https://i.imgur.com/H8slz8n.jpg",
    width: 960,
    height: 960,
  },
  {
    name: "Hamm",
    src: "https://i.imgur.com/NIZQYbv.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Cookie",
    src: "https://i.imgur.com/6OQdJLF.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Riri",
    src: "https://i.imgur.com/FFMZYZ2.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Soleil",
    src: "https://i.imgur.com/I8rXqrx.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Gracie",
    src: "https://i.imgur.com/JHUtyBB.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Wendy and Micky",
    src: "https://i.imgur.com/dyp21AH.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Luki",
    src: "https://i.imgur.com/SF43X27.jpg",
    width: 2016,
    height: 1512,
  },
  {
    name: "Elbe",
    src: "https://i.imgur.com/BKkc6WG.jpg",
    width: 2376,
    height: 4224,
  },
  {
    name: "Nash Buddy",
    src: "https://i.imgur.com/l4pPHeU.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Skittles",
    src: "https://i.imgur.com/liKkLTf.jpg",
    width: 1936,
    height: 1936,
  },
  {
    name: "Jacob",
    src: "https://i.imgur.com/eXOA2hu.jpg",
    width: 960,
    height: 1280,
  },
  {
    name: "PJ",
    src: "https://i.imgur.com/NceFCGV.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Otis",
    src: "https://i.imgur.com/IkbG0zD.jpg",
    width: 750,
    height: 1334,
  },
  {
    name: "Terrance",
    src: "https://i.imgur.com/gBnpnKN.jpg",
    width: 1080,
    height: 1920,
  },
  {
    name: "Samuel Floofington III",
    src: "https://i.imgur.com/8UkFvrO.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Rascal and Bobeep",
    src: "https://i.imgur.com/Yj6Wz4d.jpg",
    width: 1296,
    height: 972,
  },
  {
    name: "Cookie",
    src: "https://i.imgur.com/Dk51GjI.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Midnight",
    src: "https://i.imgur.com/S9DhqQz.jpg",
    width: 1638,
    height: 2048,
  },
  {
    name: "Jupiter",
    src: "https://i.imgur.com/B6GXzPW.jpg",
    width: 2744,
    height: 3662,
  },
  {
    name: "Emi-chan",
    src: "https://i.imgur.com/I0qqiZ9.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Tré Cool",
    src: "https://i.imgur.com/vySHpJO.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Luzi",
    src: "https://i.imgur.com/yNr9S0z.jpg",
    width: 2800,
    height: 3734,
  },
  {
    name: "Rübe",
    src: "https://i.imgur.com/fGSSF2E.jpg",
    width: 2800,
    height: 5271,
  },
  {
    name: "Shelldon",
    src: "https://i.imgur.com/ZMwrwKK.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Foster",
    src: "https://i.imgur.com/XpQoXxX.jpg",
    width: 1224,
    height: 1530,
  },
  {
    name: "Tafi",
    src: "https://i.imgur.com/Jhkuw4v.jpg",
    width: 2304,
    height: 1536,
  },
  {
    name: "Turbo",
    src: "https://i.imgur.com/nlp4z5o.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Mandi",
    src: "https://i.imgur.com/0Dv9vsb.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Bur'i",
    src: "https://i.imgur.com/69WWNPV.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Ban",
    src: "https://i.imgur.com/eoYIgra.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Moose",
    src: "https://i.imgur.com/qjAyb8y.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Charlie and Mason",
    src: "https://i.imgur.com/CyvZtE0.jpg",
    width: 640,
    height: 480,
  },
  {
    name: "Remi",
    src: "https://i.imgur.com/9ePii4p.jpg",
    width: 2316,
    height: 3088,
  },
  {
    name: "Henry",
    src: "https://i.imgur.com/nE8Rnne.jpg",
    width: 1122,
    height: 2208,
  },
  {
    name: "Cheyenne",
    src: "https://i.imgur.com/oqTLw58.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Hatori",
    src: "https://i.imgur.com/RSS45eq.jpg",
    width: 972,
    height: 649,
  },
  {
    name: "Yare Yare",
    src: "https://i.imgur.com/AL3FCJu.jpg",
    width: 2048,
    height: 1536,
  },
  {
    name: "John and Kelly",
    src: "https://i.imgur.com/7bst1nX.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Chaos",
    src: "https://i.imgur.com/6SVPyyB.jpg",
    width: 2744,
    height: 3662,
  },
  {
    name: "Patches",
    src: "https://i.imgur.com/iYhalY8.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Blanco",
    src: "https://i.imgur.com/AT2GbQ5.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Maya",
    src: "https://i.imgur.com/Gkp0P6M.jpg",
    width: 2448,
    height: 3264,
  },
  {
    name: "Mrs Breeches",
    src: "https://i.imgur.com/ADuY8zy.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Maya",
    src: "https://i.imgur.com/levtdTh.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Miette",
    src: "https://i.imgur.com/uxAXpTO.jpg",
    width: 2735,
    height: 3646,
  },
  {
    name: "Sirius",
    src: "https://i.imgur.com/hzpI4nV.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Sam",
    src: "https://i.imgur.com/MifDsl5.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Nicky",
    src: "https://i.imgur.com/zDHtHf4.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Chucky",
    src: "https://i.imgur.com/IIoEi9I.jpg",
    width: 1125,
    height: 1489,
  },
  {
    name: "Leo and Maggie",
    src: "https://i.imgur.com/x5hWHJB.jpg",
    width: 2500,
    height: 1667,
  },
  {
    name: "Padmè",
    src: "https://i.imgur.com/AxRy0pF.jpg",
    width: 2049,
    height: 1537,
  },
  {
    name: "Joey",
    src: "https://i.imgur.com/ixVkKF1.jpg",
    width: 1123,
    height: 2431,
  },
  {
    name: "Raiden",
    src: "https://i.imgur.com/vyYY97L.jpg",
    width: 1112,
    height: 2208,
  },
  {
    name: "Lady",
    src: "https://i.imgur.com/bL2b5JS.jpg",
    width: 2500,
    height: 1667,
  },
  {
    name: "Ti-Biscuit",
    src: "https://i.imgur.com/zPtNBH6.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Li Li",
    src: "https://i.imgur.com/Os6wYIE.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Eliott",
    src: "https://i.imgur.com/Tfho9ga.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Cutie",
    src: "https://i.imgur.com/azXsDzv.jpg",
    width: 960,
    height: 1280,
  },
  {
    name: "Angie",
    src: "https://i.imgur.com/tRwauBz.jpg",
    width: 2016,
    height: 1512,
  },
  {
    name: "Ralphonzo",
    src: "https://i.imgur.com/iI1vNEj.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Snowflake",
    src: "https://i.imgur.com/SFtQmAo.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Ghost",
    src: "https://i.imgur.com/ArPFOiB.jpg",
    width: 972,
    height: 1296,
  },
  {
    name: "Shelly, Dino, Paola, Bruna, and Gedeona",
    src: "https://i.imgur.com/L1c5Ocu.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Thad",
    src: "https://i.imgur.com/xvzcYfj.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "June",
    src: "https://i.imgur.com/xs5UXWo.jpg",
    width: 4857,
    height: 3238,
  },
  {
    name: "Gałgan",
    src: "https://i.imgur.com/fCDYdL8.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Kaia",
    src: "https://i.imgur.com/G29zFQi.jpg",
    width: 1200,
    height: 1600,
  },
  {
    name: "Oakley and Flower",
    src: "https://i.imgur.com/HkipTnT.jpg",
    width: 1599,
    height: 1185,
  },
  {
    name: "Thor",
    src: "https://i.imgur.com/U4SfbTu.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Sky",
    src: "https://i.imgur.com/Ke3OZRG.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Ebi",
    src: "https://i.imgur.com/yIELctb.jpg",
    width: 720,
    height: 1280,
  },
  {
    name: "Neferpitou",
    src: "https://i.imgur.com/hNbKTfe.jpg",
    width: 2448,
    height: 3264,
  },
  {
    name: "Luna",
    src: "https://i.imgur.com/vJVWu1M.jpg",
    width: 2048,
    height: 1536,
  },
  {
    name: "Willow",
    src: "https://i.imgur.com/9YSicvB.jpg",
    width: 1122,
    height: 2208,
  },
  {
    name: "Atilla",
    src: "https://i.imgur.com/Y1m9lwr.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Mikey",
    src: "https://i.imgur.com/BpbIDAl.jpg",
    width: 1732,
    height: 2309,
  },
  {
    name: "Tib",
    src: "https://i.imgur.com/l79nCoI.jpg",
    width: 2353,
    height: 3234,
  },
  {
    name: "Lola",
    src: "https://i.imgur.com/ih8aa8x.jpg",
    width: 2592,
    height: 2592,
  },
  {
    name: "Packo",
    src: "https://i.imgur.com/XqDRYrz.jpg",
    width: 2448,
    height: 3264,
  },
  {
    name: "Cashew (standing)",
    src: "https://i.imgur.com/SbjkMyh.jpg",
    width: 2016,
    height: 1512,
  },
  {
    name: "Mis",
    src: "https://i.imgur.com/eHrZNIo.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Rosie",
    src: "https://i.imgur.com/Nesd6US.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Simone",
    src: "https://i.imgur.com/VxlIk0L.jpg",
    width: 1509,
    height: 1656,
  },
  {
    name: "Stilinski",
    src: "https://i.imgur.com/XZmNV95.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Chleb",
    src: "https://i.imgur.com/uUCuMgO.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Shigure",
    src: "https://i.imgur.com/OmRZMjp.jpg",
    width: 1512,
    height: 2016,
  },
  {
    name: "Sky",
    src: "https://i.imgur.com/TQVL0Ev.jpg",
    width: 2616,
    height: 2005,
  },
  {
    name: "Koa and Kyro",
    src: "https://i.imgur.com/EZSUrGf.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Triton, Lab and Hawk",
    src: "https://i.imgur.com/DrFe8dR.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Kiki",
    src: "https://i.imgur.com/NxFZ7vt.jpg",
    width: 2048,
    height: 1536,
  },
  {
    name: "Flomster",
    src: "https://i.imgur.com/dWo6bMt.jpg",
    width: 1125,
    height: 1999,
  },
  {
    name: "Forsythe",
    src: "https://i.imgur.com/BMSqTxZ.jpg",
    width: 2048,
    height: 1536,
  },
  {
    name: "Kibby",
    src: "https://i.imgur.com/Nwb5KoD.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Myrtle",
    src: "https://i.imgur.com/tkitWgJ.jpg",
    width: 1024,
    height: 1024,
  },
  {
    name: "Nara",
    src: "https://i.imgur.com/5yKK1CE.jpg",
    width: 900,
    height: 1200,
  },
  {
    name: "Chunk",
    src: "https://i.imgur.com/9JsIGHB.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Loki",
    src: "https://i.imgur.com/VIfSduO.jpg",
    width: 1842,
    height: 2049,
  },
  {
    name: "Annabelle",
    src: "https://i.imgur.com/y3ZyejY.jpg",
    width: 3000,
    height: 1688,
  },
  {
    name: "Semmie and Toby",
    src: "https://i.imgur.com/52g2gkd.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Riley",
    src: "https://i.imgur.com/KSA3UPd.jpg",
    width: 1506,
    height: 1000,
  },
  {
    name: "Tofu",
    src: "https://i.imgur.com/qQprchd.jpg",
    width: 2320,
    height: 2900,
  },
  {
    name: "Gus",
    src: "https://i.imgur.com/P9aY58Z.jpg",
    width: 3000,
    height: 1688,
  },
  {
    name: "Jenny",
    src: "https://i.imgur.com/7Bw0km4.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Sadie",
    src: "https://i.imgur.com/lKW3sBz.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Copper",
    src: "https://i.imgur.com/1BNIm3u.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Elvira",
    src: "https://i.imgur.com/iDqjlPd.jpg",
    width: 900,
    height: 1600,
  },
  {
    name: "Rooster",
    src: "https://i.imgur.com/6vbLFn6.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Lucci",
    src: "https://i.imgur.com/Xprrj78.jpg",
    width: 1512,
    height: 2016,
  },
  {
    name: "Ollie",
    src: "https://i.imgur.com/pN8vYXs.jpg",
    width: 854,
    height: 1280,
  },
  {
    name: "Hadley",
    src: "https://i.imgur.com/soqnzrn.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Ella",
    src: "https://i.imgur.com/YrSbL2O.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Hagrid",
    src: "https://i.imgur.com/7B9ziNY.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Terra",
    src: "https://i.imgur.com/KzsOQCa.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Charlie and Freya",
    src: "https://i.imgur.com/8teJXK1.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Shrek",
    src: "https://i.imgur.com/GrCLJvL.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Diamond",
    src: "https://i.imgur.com/9zbzPHy.jpg",
    width: 2268,
    height: 4032,
  },
  {
    name: "Charlotte",
    src: "https://i.imgur.com/8I8TI2M.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Yoshi",
    src: "https://i.imgur.com/7gaDkCA.jpg",
    width: 2316,
    height: 3088,
  },
  {
    name: "Sanic",
    src: "https://i.imgur.com/X0jrcb2.jpg",
    width: 320,
    height: 240,
  },
  {
    name: "Akira",
    src: "https://i.imgur.com/wjbnjok.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Meepinator",
    src: "https://i.imgur.com/nfkGplA.jpg",
    width: 1512,
    height: 2016,
  },
  {
    name: "Barkly and Crumpet",
    src: "https://i.imgur.com/CSynLAi.jpg",
    width: 1512,
    height: 2016,
  },
  {
    name: "Kirby",
    src: "https://i.imgur.com/dTzuSov.jpg",
    width: 2448,
    height: 3264,
  },
  {
    name: "Anthony",
    src: "https://i.imgur.com/1OQmfFJ.jpg",
    width: 1374,
    height: 1832,
  },
  {
    name: "Doctor",
    src: "https://i.imgur.com/WfUgdaz.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Ludwig",
    src: "https://i.imgur.com/aRu69og.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Beckett",
    src: "https://i.imgur.com/KQtS0x0.jpg",
    width: 1122,
    height: 2208,
  },
  {
    name: "Elfie",
    src: "https://i.imgur.com/RGUNkFt.jpg",
    width: 1200,
    height: 1600,
  },
  {
    name: "Bailey",
    src: "https://i.imgur.com/fjkLU0g.jpg",
    width: 2529,
    height: 3609,
  },
  {
    name: "Quinzy",
    src: "https://i.imgur.com/lA3yPsZ.jpg",
    width: 972,
    height: 1296,
  },
  {
    name: "Max and Momo",
    src: "https://i.imgur.com/Xky7Bol.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Peach",
    src: "https://i.imgur.com/iV53f1O.jpg",
    width: 3375,
    height: 2333,
  },
  {
    name: "Buksie",
    src: "https://i.imgur.com/JIGd1h0.jpg",
    width: 2049,
    height: 1537,
  },
  {
    name: "Lily",
    src: "https://i.imgur.com/PnbjKhE.jpg",
    width: 2000,
    height: 2667,
  },
  {
    name: "Chew-Barker and Skye",
    src: "https://i.imgur.com/ZQyiA6v.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Bau",
    src: "https://i.imgur.com/C1hVK3k.jpg",
    width: 2880,
    height: 2160,
  },
  {
    name: "Basil Hayden",
    src: "https://i.imgur.com/8W5cT8g.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Garfield",
    src: "https://i.imgur.com/TlmrTAm.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Yuki and Kyo",
    src: "https://i.imgur.com/nZieIv4.jpg",
    width: 2955,
    height: 2645,
  },
  {
    name: "Oats",
    src: "https://i.imgur.com/PG3aPQZ.jpg",
    width: 2016,
    height: 1512,
  },
  {
    name: "Cola de Rayo",
    src: "https://i.imgur.com/VDSPfCr.jpg",
    width: 1472,
    height: 828,
  },
  {
    name: "Chocolatier",
    src: "https://i.imgur.com/NvuCRXm.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Ferris",
    src: "https://i.imgur.com/uIlocSw.jpg",
    width: 1650,
    height: 1906,
  },
  {
    name: "Marley",
    src: "https://i.imgur.com/TDU8VAK.jpg",
    width: 1560,
    height: 2718,
  },
  {
    name: "Caramel",
    src: "https://i.imgur.com/t14IFvO.jpg",
    width: 4272,
    height: 2848,
  },
  {
    name: "Reyna",
    src: "https://i.imgur.com/JJRRlma.jpg",
    width: 2449,
    height: 3341,
  },
  {
    name: "Kiwi",
    src: "https://i.imgur.com/PV9O2cG.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Marvin",
    src: "https://i.imgur.com/XilfhmQ.jpg",
    width: 960,
    height: 1280,
  },
  {
    name: "Waterwood",
    src: "https://i.imgur.com/v2e7fF8.jpg",
    width: 2048,
    height: 1536,
  },
  {
    name: "Triumph",
    src: "https://i.imgur.com/xiSMyoc.jpg",
    width: 3264,
    height: 2448,
  },
  {
    name: "Clash",
    src: "https://i.imgur.com/eSWDBok.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Black",
    src: "https://i.imgur.com/Clz2OTA.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Missy",
    src: "https://i.imgur.com/XcA9KJu.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Toothless",
    src: "https://i.imgur.com/Fy1BoTB.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Vladimir",
    src: "https://i.imgur.com/Dhp0C9F.jpg",
    width: 1600,
    height: 1200,
  },
  {
    name: "Gubgub",
    src: "https://i.imgur.com/ub0ruqB.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Mia",
    src: "https://i.imgur.com/JOzi5ya.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Millie",
    src: "https://i.imgur.com/GivjggS.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Tigger",
    src: "https://i.imgur.com/d2QICjl.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Jasmine",
    src: "https://i.imgur.com/ZP0c8jg.jpg",
    width: 1224,
    height: 1632,
  },
  {
    name: "Draco",
    src: "https://i.imgur.com/u9bh9X5.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Dieter",
    src: "https://i.imgur.com/iXcHPrw.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Sofia",
    src: "https://i.imgur.com/BRJYRL1.jpg",
    width: 2500,
    height: 1605,
  },
  {
    name: "Azlan and Skerp",
    src: "https://i.imgur.com/WgoEZdo.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Chad",
    src: "https://i.imgur.com/WKBXyNI.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Aspen",
    src: "https://i.imgur.com/uKohZHc.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Yago",
    src: "https://i.imgur.com/HbljiDz.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Jake",
    src: "https://i.imgur.com/8a1vLkK.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Myggan and Rakel",
    src: "https://i.imgur.com/uAVat73.jpg",
    width: 2204,
    height: 2204,
  },
  {
    name: "Trooper",
    src: "https://i.imgur.com/mD7LUeg.jpg",
    width: 2448,
    height: 3264,
  },
  {
    name: "Farmer Kane",
    src: "https://i.imgur.com/AWQG2Mf.jpg",
    width: 499,
    height: 750,
  },
  {
    name: "Pebble",
    src: "https://i.imgur.com/Om9Cwcz.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Ham",
    src: "https://i.imgur.com/AtCSKB5.jpg",
    width: 1512,
    height: 2016,
  },
  {
    name: "Racal",
    src: "https://i.imgur.com/MrlKghE.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Levi",
    src: "https://i.imgur.com/qA7SUOp.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Jack",
    src: "https://i.imgur.com/7ZkLC8l.jpg",
    width: 2160,
    height: 3840,
  },
  {
    name: "Mac",
    src: "https://i.imgur.com/Tvg8sew.jpg",
    width: 960,
    height: 1280,
  },
  {
    name: "Joker",
    src: "https://i.imgur.com/Qf0Dp61.jpg",
    width: 2500,
    height: 1667,
  },
  {
    name: "Ookla",
    src: "https://i.imgur.com/iWodTI2.jpg",
    width: 3264,
    height: 2448,
  },
  {
    name: "Nola",
    src: "https://i.imgur.com/N1fhnVU.jpg",
    width: 739,
    height: 1051,
  },
  {
    name: "Mugsy",
    src: "https://i.imgur.com/4EYuAWp.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Louie",
    src: "https://i.imgur.com/btb6Q0S.jpg",
    width: 434,
    height: 1024,
  },
  {
    name: "Pablo",
    src: "https://i.imgur.com/Qh3P7aS.jpg",
    width: 1872,
    height: 2505,
  },
  {
    name: "Bella",
    src: "https://i.imgur.com/rQs8mJ3.jpg",
    width: 2985,
    height: 2992,
  },
  {
    name: "Guria",
    src: "https://i.imgur.com/zzi7TeD.jpg",
    width: 2929,
    height: 2016,
  },
  {
    name: "Ruby",
    src: "https://i.imgur.com/UvZ2Nx7.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Lilo",
    src: "https://i.imgur.com/V1UQ22t.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Bella",
    src: "https://i.imgur.com/jYfz8IF.jpg",
    width: 2688,
    height: 1520,
  },
  {
    name: "Bibi",
    src: "https://i.imgur.com/okQEey3.jpg",
    width: 2048,
    height: 1536,
  },
  {
    name: "Emi",
    src: "https://i.imgur.com/43WvADA.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Harper",
    src: "https://i.imgur.com/l4TJ6oh.jpg",
    width: 768,
    height: 1024,
  },
  {
    name: "Milo",
    src: "https://i.imgur.com/cn5A5UV.jpg",
    width: 480,
    height: 640,
  },
  {
    name: "Mako",
    src: "https://i.imgur.com/gfERXkz.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Lucy",
    src: "https://i.imgur.com/3XCVGJI.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Harley",
    src: "https://i.imgur.com/HoUA30B.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Ginger and Mary-Ann",
    src: "https://i.imgur.com/HZuq1xc.jpg",
    width: 2221,
    height: 1777,
  },
  {
    name: "Hank",
    src: "https://i.imgur.com/YNgn3kT.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Ana and Tracer",
    src: "https://i.imgur.com/SQqkLE3.jpg",
    width: 1125,
    height: 1874,
  },
  {
    name: "Andy",
    src: "https://i.imgur.com/LkiLnqR.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Bandito",
    src: "https://i.imgur.com/2qzJNFa.jpg",
    width: 3574,
    height: 3024,
  },
  {
    name: "Alfred",
    src: "https://i.imgur.com/mpOmohY.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Leo",
    src: "https://i.imgur.com/Kxz0Djc.jpg",
    width: 1080,
    height: 1165,
  },
  {
    name: "Berlin",
    src: "https://i.imgur.com/OdUIZSm.jpg",
    width: 480,
    height: 640,
  },
  {
    name: "Noel",
    src: "https://i.imgur.com/NpZIuQk.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Charlie",
    src: "https://i.imgur.com/Zv9HIOv.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Carl",
    src: "https://i.imgur.com/5xhNdVR.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Wolfgang",
    src: "https://i.imgur.com/a1jQhRh.jpg",
    width: 2490,
    height: 3320,
  },
  {
    name: "Duke",
    src: "https://i.imgur.com/DdwYjxN.jpg",
    width: 3000,
    height: 2000,
  },
  {
    name: "Grist",
    src: "https://i.imgur.com/CIMujiP.jpg",
    width: 2349,
    height: 2349,
  },
  {
    name: "Ringo",
    src: "https://i.imgur.com/qi4Mz1a.jpg",
    width: 3888,
    height: 2592,
  },
  {
    name: "Asta",
    src: "https://i.imgur.com/iWczDsJ.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Buddy",
    src: "https://i.imgur.com/nGslHh8.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Odin",
    src: "https://i.imgur.com/ORwpUbH.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Nibbler",
    src: "https://i.imgur.com/LqyGNGn.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Maxwell Appleton II",
    src: "https://i.imgur.com/E6aEHk3.jpg",
    width: 2016,
    height: 1512,
  },
  {
    name: "Taco",
    src: "https://i.imgur.com/szrScj9.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Howl",
    src: "https://i.imgur.com/zNzDoOn.jpg",
    width: 2500,
    height: 2000,
  },
  {
    name: "Winnie",
    src: "https://i.imgur.com/HdWiZYV.jpg",
    width: 2782,
    height: 2782,
  },
  {
    name: "Gibbs",
    src: "https://i.imgur.com/tdYijm8.jpg",
    width: 2851,
    height: 2138,
  },
  {
    name: "Luna",
    src: "https://i.imgur.com/MBfeFpL.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Cowboy",
    src: "https://i.imgur.com/TZDTHjW.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Zoey",
    src: "https://i.imgur.com/G2gpg3S.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Lady",
    src: "https://i.imgur.com/4sFDb3X.jpg",
    width: 750,
    height: 1334,
  },
  {
    name: "Ollie",
    src: "https://i.imgur.com/sFcp2ZO.jpg",
    width: 768,
    height: 1024,
  },
  {
    name: "Slater",
    src: "https://i.imgur.com/jfKJV7R.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Lulu",
    src: "https://i.imgur.com/slmQnLM.jpg",
    width: 2048,
    height: 1536,
  },
  {
    name: "Luna",
    src: "https://i.imgur.com/HgPNmD8.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Lola",
    src: "https://i.imgur.com/X2VhGjx.jpg",
    width: 1772,
    height: 1772,
  },
  {
    name: "Rocky",
    src: "https://i.imgur.com/zUfJioC.jpg",
    width: 480,
    height: 640,
  },
  {
    name: "Pita",
    src: "https://i.imgur.com/kx8u9Y1.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Messi",
    src: "https://i.imgur.com/5FFj1bo.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Shelby and Dino",
    src: "https://i.imgur.com/icm6miq.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Roux",
    src: "https://i.imgur.com/BRoX0Qd.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Bagel",
    src: "https://i.imgur.com/R7bPSP3.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Tippie",
    src: "https://i.imgur.com/aoZ0K83.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Chopper",
    src: "https://i.imgur.com/r9yfy5E.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Zoey",
    src: "https://i.imgur.com/Q5ouBcI.jpg",
    width: 1536,
    height: 2048,
  },
  {
    name: "Dynamite and Napolean",
    src: "https://i.imgur.com/xth8W6w.jpg",
    width: 2016,
    height: 1512,
  },
  {
    name: "Cleo",
    src: "https://i.imgur.com/h71uUtM.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Angus and Sabrina",
    src: "https://i.imgur.com/ZrSteaO.jpg",
    width: 2500,
    height: 1406,
  },
  {
    name: "Oakley",
    src: "https://i.imgur.com/VnN1uJU.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Maze",
    src: "https://i.imgur.com/ZdwpHEw.jpg",
    width: 2673,
    height: 3832,
  },
  {
    name: "Grey and Old Bill",
    src: "https://i.imgur.com/oGP9des.jpg",
    width: 1544,
    height: 1158,
  },
  {
    name: "Gallifrey",
    src: "https://i.imgur.com/IfrEjLJ.jpg",
    width: 768,
    height: 1024,
  },
  {
    name: "Ziggy and Marlo",
    src: "https://i.imgur.com/AHeaun1.jpg",
    width: 2218,
    height: 2773,
  },
  {
    name: "Marley",
    src: "https://i.imgur.com/J5FpZ2y.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Qwerty",
    src: "https://i.imgur.com/fi1sGls.jpg",
    width: 2500,
    height: 1875,
  },
  {
    name: "Nala",
    src: "https://i.imgur.com/1BwIEP5.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Hoagie",
    src: "https://i.imgur.com/6zIRcdo.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Apostrophe",
    src: "https://i.imgur.com/GDU3Mq6.jpg",
    width: 665,
    height: 1182,
  },
  {
    name: "Lily",
    src: "https://i.imgur.com/XVbOG9d.jpg",
    width: 2048,
    height: 1536,
  },
  {
    name: "Scout",
    src: "https://i.imgur.com/t9hsDKU.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Izzy",
    src: "https://i.imgur.com/o3iQ9EP.jpg",
    width: 1638,
    height: 2060,
  },
  {
    name: "Newton",
    src: "https://i.imgur.com/O0pvBho.png",
    width: 750,
    height: 992,
  },
  {
    name: "Doc",
    src: "https://i.imgur.com/psMIpTy.png",
    width: 720,
    height: 1280,
  },
  {
    name: "Jake",
    src: "https://i.imgur.com/roBvd8v.jpg",
    width: 2000,
    height: 2500,
  },
  {
    name: "Sly",
    src: "https://i.imgur.com/eWpiaCH.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Bear",
    src: "https://i.imgur.com/UO9LdHM.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Phoenix",
    src: "https://i.imgur.com/hXaEqmH.png",
    width: 1279,
    height: 959,
  },
  {
    name: "Penny and Pearl",
    src: "https://i.imgur.com/qVjDTGp.jpg",
    width: 1334,
    height: 1000,
  },
  {
    name: "Pixelita",
    src: "https://i.imgur.com/fRvCg25.jpg",
    width: 828,
    height: 863,
  },
  {
    name: "Maggie",
    src: "https://i.imgur.com/US6D4dK.png",
    width: 1084,
    height: 1726,
  },
  {
    name: "Emmett",
    src: "https://i.imgur.com/3tXyKEJ.png",
    width: 1242,
    height: 1082,
  },
  {
    name: "Baxter",
    src: "https://i.imgur.com/NmdW2d4.png",
    width: 1125,
    height: 1129,
  },
  {
    name: "Padme",
    src: "https://i.imgur.com/y1cM09i.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Julieta",
    src: "https://i.imgur.com/vhK1rOz.jpg",
    width: 960,
    height: 1280,
  },
  {
    name: "Borgoña and Clery",
    src: "https://i.imgur.com/gczS1rd.jpg",
    width: 4032,
    height: 3024,
  },
  {
    name: "Jax",
    src: "https://i.imgur.com/Zc49C65.jpg",
    width: 1112,
    height: 2208,
  },
  {
    name: "Gracie",
    src: "https://i.imgur.com/mmIBuK2.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Tommy",
    src: "https://i.imgur.com/I6qlOKu.jpg",
    width: 2448,
    height: 3264,
  },
  {
    name: "Sissy",
    src: "https://i.imgur.com/pxtAncU.jpg",
    width: 3024,
    height: 4032,
  },
  {
    name: "Pepe",
    src: "https://i.imgur.com/BOlsZsn.jpg",
    width: 1200,
    height: 1600,
  },
  {
    name: "Koji",
    src: "https://i.imgur.com/eLC6HSp.jpg",
    width: 1122,
    height: 2208,
  },
  {
    name: "Tiger",
    src: "https://i.imgur.com/z0Xv7UJ.jpg",
    width: 3872,
    height: 2592,
  },
  {
    name: "Tucker",
    src: "https://i.imgur.com/ky52Y40.jpg",
    width: 2500,
    height: 3333,
  },
  {
    name: "Amy",
    src: "https://i.imgur.com/aF86777.jpg",
    width: 1200,
    height: 1600,
  },
];
